[project]
name = "model-comparative-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.3.13",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "scipy>=1.16.3",
    "tensorflow==2.19",
]
